/*
Spotify Web API with fixes and improvements from sonallux

You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 

API version: 2023.6.7
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AudiobookObjectAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AudiobookObjectAllOf{}

// AudiobookObjectAllOf struct for AudiobookObjectAllOf
type AudiobookObjectAllOf struct {
	Chapters AudiobookObjectAllOfChapters `json:"chapters"`
}

// NewAudiobookObjectAllOf instantiates a new AudiobookObjectAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAudiobookObjectAllOf(chapters AudiobookObjectAllOfChapters) *AudiobookObjectAllOf {
	this := AudiobookObjectAllOf{}
	this.Chapters = chapters
	return &this
}

// NewAudiobookObjectAllOfWithDefaults instantiates a new AudiobookObjectAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAudiobookObjectAllOfWithDefaults() *AudiobookObjectAllOf {
	this := AudiobookObjectAllOf{}
	return &this
}

// GetChapters returns the Chapters field value
func (o *AudiobookObjectAllOf) GetChapters() AudiobookObjectAllOfChapters {
	if o == nil {
		var ret AudiobookObjectAllOfChapters
		return ret
	}

	return o.Chapters
}

// GetChaptersOk returns a tuple with the Chapters field value
// and a boolean to check if the value has been set.
func (o *AudiobookObjectAllOf) GetChaptersOk() (*AudiobookObjectAllOfChapters, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chapters, true
}

// SetChapters sets field value
func (o *AudiobookObjectAllOf) SetChapters(v AudiobookObjectAllOfChapters) {
	o.Chapters = v
}

func (o AudiobookObjectAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AudiobookObjectAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chapters"] = o.Chapters
	return toSerialize, nil
}

type NullableAudiobookObjectAllOf struct {
	value *AudiobookObjectAllOf
	isSet bool
}

func (v NullableAudiobookObjectAllOf) Get() *AudiobookObjectAllOf {
	return v.value
}

func (v *NullableAudiobookObjectAllOf) Set(val *AudiobookObjectAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAudiobookObjectAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAudiobookObjectAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudiobookObjectAllOf(val *AudiobookObjectAllOf) *NullableAudiobookObjectAllOf {
	return &NullableAudiobookObjectAllOf{value: val, isSet: true}
}

func (v NullableAudiobookObjectAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudiobookObjectAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


